#!/bin/bash
# SCION MiniNet Setup Script
# Generates all configuration files for the local SCION network

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
GEN_DIR="$PROJECT_DIR/gen"

echo "📁 Creating directory structure..."
mkdir -p "$GEN_DIR"/{AS110,AS111,AS210,AS211}/{crypto/as,certs,keys}

# ============================================
# Network Configuration
# ============================================
# AS110 (ISD1 Core): 172.20.0.10-12
# AS111 (ISD1 Leaf): 172.20.0.20-23
# AS210 (ISD2 Core): 172.20.0.30-32
# AS211 (ISD2 Leaf): 172.20.0.40-43

echo "🔐 Generating PKI keys and certificates..."

# Generate TRC (Trust Root Configuration) for each ISD
generate_trc() {
    local isd=$1
    local dir=$2
    # In a real setup, this would use scion-pki
    # For learning purposes, we create placeholder files
    cat > "$dir/certs/ISD${isd}.trc" << EOF
{
  "isd": ${isd},
  "version": 1,
  "description": "ISD ${isd} Trust Root Configuration"
}
EOF
}

# Generate AS certificate
generate_as_cert() {
    local isd=$1
    local as=$2
    local dir=$3
    cat > "$dir/certs/ISD${isd}-AS${as}.pem" << EOF
-----BEGIN CERTIFICATE-----
Placeholder certificate for AS ${isd}-ff00:0:${as}
This is a self-contained demo - real certs would be generated by scion-pki
-----END CERTIFICATE-----
EOF
}

# Generate AS private key
generate_as_key() {
    local dir=$1
    cat > "$dir/keys/as-signing.key" << 'EOF'
-----BEGIN PRIVATE KEY-----
Placeholder private key for demo purposes
-----END PRIVATE KEY-----
EOF
}

echo "📝 Generating topology files..."

# AS 1-ff00:0:110 (ISD1 Core)
cat > "$GEN_DIR/AS110/topology.json" << 'EOF'
{
  "isd_as": "1-ff00:0:110",
  "mtu": 1472,
  "dispatched_ports": "1024-65535",
  "attributes": ["core"],
  "border_routers": {
    "br-110": {
      "internal_addr": "172.20.0.10:30001",
      "interfaces": {
        "1": {
          "underlay": {
            "local": "172.20.0.10:50001",
            "remote": "172.20.0.30:50001"
          },
          "isd_as": "2-ff00:0:210",
          "link_to": "CORE",
          "mtu": 1472
        },
        "2": {
          "underlay": {
            "local": "172.20.0.10:50002",
            "remote": "172.20.0.20:50001"
          },
          "isd_as": "1-ff00:0:111",
          "link_to": "CHILD",
          "mtu": 1472
        }
      }
    }
  },
  "control_service": {
    "cs-110": {
      "addr": "172.20.0.10:30252"
    }
  }
}
EOF

# AS 1-ff00:0:111 (ISD1 Leaf)
cat > "$GEN_DIR/AS111/topology.json" << 'EOF'
{
  "isd_as": "1-ff00:0:111",
  "mtu": 1472,
  "dispatched_ports": "1024-65535",
  "attributes": [],
  "border_routers": {
    "br-111": {
      "internal_addr": "172.20.0.20:30001",
      "interfaces": {
        "1": {
          "underlay": {
            "local": "172.20.0.20:50001",
            "remote": "172.20.0.10:50002"
          },
          "isd_as": "1-ff00:0:110",
          "link_to": "PARENT",
          "mtu": 1472
        },
        "2": {
          "underlay": {
            "local": "172.20.0.20:50002",
            "remote": "172.20.0.40:50002"
          },
          "isd_as": "2-ff00:0:211",
          "link_to": "PEER",
          "mtu": 1472
        }
      }
    }
  },
  "control_service": {
    "cs-111": {
      "addr": "172.20.0.20:30252"
    }
  }
}
EOF

# AS 2-ff00:0:210 (ISD2 Core)
cat > "$GEN_DIR/AS210/topology.json" << 'EOF'
{
  "isd_as": "2-ff00:0:210",
  "mtu": 1472,
  "dispatched_ports": "1024-65535",
  "attributes": ["core"],
  "border_routers": {
    "br-210": {
      "internal_addr": "172.20.0.30:30001",
      "interfaces": {
        "1": {
          "underlay": {
            "local": "172.20.0.30:50001",
            "remote": "172.20.0.10:50001"
          },
          "isd_as": "1-ff00:0:110",
          "link_to": "CORE",
          "mtu": 1472
        },
        "2": {
          "underlay": {
            "local": "172.20.0.30:50002",
            "remote": "172.20.0.40:50001"
          },
          "isd_as": "2-ff00:0:211",
          "link_to": "CHILD",
          "mtu": 1472
        }
      }
    }
  },
  "control_service": {
    "cs-210": {
      "addr": "172.20.0.30:30252"
    }
  }
}
EOF

# AS 2-ff00:0:211 (ISD2 Leaf)
cat > "$GEN_DIR/AS211/topology.json" << 'EOF'
{
  "isd_as": "2-ff00:0:211",
  "mtu": 1472,
  "dispatched_ports": "1024-65535",
  "attributes": [],
  "border_routers": {
    "br-211": {
      "internal_addr": "172.20.0.40:30001",
      "interfaces": {
        "1": {
          "underlay": {
            "local": "172.20.0.40:50001",
            "remote": "172.20.0.30:50002"
          },
          "isd_as": "2-ff00:0:210",
          "link_to": "PARENT",
          "mtu": 1472
        },
        "2": {
          "underlay": {
            "local": "172.20.0.40:50002",
            "remote": "172.20.0.20:50002"
          },
          "isd_as": "1-ff00:0:111",
          "link_to": "PEER",
          "mtu": 1472
        }
      }
    }
  },
  "control_service": {
    "cs-211": {
      "addr": "172.20.0.40:30252"
    }
  }
}
EOF

echo "⚙️  Generating service configurations..."

# Generate Control Service configs
for as in 110 111 210 211; do
    cat > "$GEN_DIR/AS${as}/cs.toml" << EOF
[general]
id = "cs-${as}"
config_dir = "/etc/scion"

[log.console]
level = "debug"

[beacon_db]
connection = "/var/lib/scion/cs-${as}.beacon.db"

[path_db]
connection = "/var/lib/scion/cs-${as}.path.db"

[trust_db]
connection = "/var/lib/scion/cs-${as}.trust.db"
EOF
done

# Generate Border Router configs
for as in 110 111 210 211; do
    cat > "$GEN_DIR/AS${as}/br.toml" << EOF
[general]
id = "br-${as}"
config_dir = "/etc/scion"

[log.console]
level = "debug"
EOF
done

# Generate SCION Daemon configs
for as in 110 111 210 211; do
    sd_addr="172.20.0.$((as == 110 ? 10 : (as == 111 ? 20 : (as == 210 ? 30 : 40))))"
    cat > "$GEN_DIR/AS${as}/sd.toml" << EOF
[general]
id = "sd-${as}"
config_dir = "/etc/scion"

[log.console]
level = "debug"

[sd]
address = "${sd_addr}:30255"

[trust_db]
connection = "/var/lib/scion/sd-${as}.trust.db"

[path_db]
connection = "/var/lib/scion/sd-${as}.path.db"
EOF
done

# Generate dispatcher config for each AS with specific underlay address
for as in 110 111 210 211; do
    underlay_ip="172.20.0.$((as == 110 ? 10 : (as == 111 ? 20 : (as == 210 ? 30 : 40))))"
    cat > "$GEN_DIR/AS${as}/dispatcher.toml" << EOF
[dispatcher]
id = "dispatcher"
underlay_addr = "${underlay_ip}"

[log]
console.level = "debug"
EOF
done

# ============================================
# PKI Generation (using scion-pki in Docker)
# ============================================
echo "🔐 Generating PKI using scion-pki..."

# Check if Docker image exists, build if not
if ! docker image inspect scionmininet-as110 &>/dev/null; then
    echo "  Building Docker image first..."
    docker compose build as110
fi

# Run PKI generation script inside a container
docker run --rm -v "$PROJECT_DIR/scripts:/scripts:ro" -v "$GEN_DIR:/gen" \
    --entrypoint /bin/bash scionmininet-as110 -c "
set -e

PKI_DIR='/tmp/pki'
rm -rf \"\$PKI_DIR\"
mkdir -p \"\$PKI_DIR\"/{ISD1,ISD2}
cd \"\$PKI_DIR\"

echo '  Creating ISD 1 PKI...'
mkdir -p ISD1/AS110 ISD1/AS111

# Generate AS110 (core) keys and certs
scion-pki key private ISD1/AS110/cp-root.key 2>/dev/null
scion-pki key private ISD1/AS110/cp-voting.key 2>/dev/null
scion-pki key private ISD1/AS110/cp-regular.key 2>/dev/null
scion-pki key private ISD1/AS110/as-signing.key 2>/dev/null
scion-pki key symmetric ISD1/AS110/master0.key 2>/dev/null
scion-pki key symmetric ISD1/AS110/master1.key 2>/dev/null

# Create certificate templates
echo '{\"isd_as\": \"1-ff00:0:110\", \"common_name\": \"1-ff00:0:110 Root Certificate\"}' > ISD1/AS110/cp-root.json
echo '{\"isd_as\": \"1-ff00:0:110\", \"common_name\": \"1-ff00:0:110 Sensitive Voting Certificate\"}' > ISD1/AS110/cp-voting.json
echo '{\"isd_as\": \"1-ff00:0:110\", \"common_name\": \"1-ff00:0:110 Regular Voting Certificate\"}' > ISD1/AS110/cp-regular.json

# Generate certificates
scion-pki certificate create --force --profile=cp-root \
    --not-before=2024-01-01T00:00:00Z --not-after=2027-01-01T00:00:00Z \
    --key ISD1/AS110/cp-root.key \
    ISD1/AS110/cp-root.json ISD1/AS110/cp-root.crt ISD1/AS110/cp-root.key

scion-pki certificate create --force --profile=sensitive-voting \
    --not-before=2024-01-01T00:00:00Z --not-after=2027-01-01T00:00:00Z \
    --key ISD1/AS110/cp-voting.key \
    ISD1/AS110/cp-voting.json ISD1/AS110/cp-voting.crt ISD1/AS110/cp-voting.key

scion-pki certificate create --force --profile=regular-voting \
    --not-before=2024-01-01T00:00:00Z --not-after=2027-01-01T00:00:00Z \
    --key ISD1/AS110/cp-regular.key \
    ISD1/AS110/cp-regular.json ISD1/AS110/cp-regular.crt ISD1/AS110/cp-regular.key

# Create TRC for ISD1
cat > ISD1/trc-template.toml << 'TRCEOF'
isd = 1
description = \"ISD 1 - Academic Network\"
serial_version = 1
base_version = 1
voting_quorum = 1

core_ases = [\"ff00:0:110\"]
authoritative_ases = [\"ff00:0:110\"]
cert_files = [\"AS110/cp-root.crt\", \"AS110/cp-voting.crt\", \"AS110/cp-regular.crt\"]

no_trust_reset = false

[validity]
not_before = 1704067200
validity = \"1096d\"
TRCEOF

scion-pki trc payload --template ISD1/trc-template.toml --out ISD1/trc-payload.der
scion-pki trc sign ISD1/trc-payload.der ISD1/AS110/cp-voting.crt ISD1/AS110/cp-voting.key \
    --out ISD1/ISD1-B1-S1.trc

# Generate CA certificate
echo '{\"isd_as\": \"1-ff00:0:110\", \"common_name\": \"1-ff00:0:110 CA Certificate\"}' > ISD1/AS110/cp-ca.json
scion-pki key private ISD1/AS110/cp-ca.key 2>/dev/null
scion-pki certificate create --force --profile=cp-ca \
    --ca ISD1/AS110/cp-root.crt --ca-key ISD1/AS110/cp-root.key \
    --not-before=2024-01-01T00:00:00Z --not-after=2027-01-01T00:00:00Z \
    --key ISD1/AS110/cp-ca.key \
    ISD1/AS110/cp-ca.json ISD1/AS110/cp-ca.crt ISD1/AS110/cp-ca.key

# Generate AS certificate for AS110 (core AS also needs AS cert for signing)
echo '{\"isd_as\": \"1-ff00:0:110\", \"common_name\": \"1-ff00:0:110 AS Certificate\"}' > ISD1/AS110/cp-as.json
scion-pki key private ISD1/AS110/cp-as.key 2>/dev/null
scion-pki certificate create --force --profile=cp-as --bundle \
    --ca ISD1/AS110/cp-ca.crt --ca-key ISD1/AS110/cp-ca.key \
    --not-before=2024-01-01T00:00:00Z --not-after=2026-01-01T00:00:00Z \
    --key ISD1/AS110/cp-as.key \
    ISD1/AS110/cp-as.json ISD1/AS110/cp-as.pem ISD1/AS110/cp-as.key

# Generate AS111 (non-core) PKI
scion-pki key private ISD1/AS111/cp-as.key 2>/dev/null
scion-pki key symmetric ISD1/AS111/master0.key 2>/dev/null
scion-pki key symmetric ISD1/AS111/master1.key 2>/dev/null
echo '{\"isd_as\": \"1-ff00:0:111\", \"common_name\": \"1-ff00:0:111 AS Certificate\"}' > ISD1/AS111/cp-as.json
scion-pki certificate create --force --profile=cp-as --bundle \
    --ca ISD1/AS110/cp-ca.crt --ca-key ISD1/AS110/cp-ca.key \
    --not-before=2024-01-01T00:00:00Z --not-after=2026-01-01T00:00:00Z \
    --key ISD1/AS111/cp-as.key \
    ISD1/AS111/cp-as.json ISD1/AS111/cp-as.pem ISD1/AS111/cp-as.key

echo '  Creating ISD 2 PKI...'
mkdir -p ISD2/AS210 ISD2/AS211

# Generate AS210 (core) keys and certs
scion-pki key private ISD2/AS210/cp-root.key 2>/dev/null
scion-pki key private ISD2/AS210/cp-voting.key 2>/dev/null
scion-pki key private ISD2/AS210/cp-regular.key 2>/dev/null
scion-pki key private ISD2/AS210/as-signing.key 2>/dev/null
scion-pki key symmetric ISD2/AS210/master0.key 2>/dev/null
scion-pki key symmetric ISD2/AS210/master1.key 2>/dev/null

echo '{\"isd_as\": \"2-ff00:0:210\", \"common_name\": \"2-ff00:0:210 Root Certificate\"}' > ISD2/AS210/cp-root.json
echo '{\"isd_as\": \"2-ff00:0:210\", \"common_name\": \"2-ff00:0:210 Sensitive Voting Certificate\"}' > ISD2/AS210/cp-voting.json
echo '{\"isd_as\": \"2-ff00:0:210\", \"common_name\": \"2-ff00:0:210 Regular Voting Certificate\"}' > ISD2/AS210/cp-regular.json

scion-pki certificate create --force --profile=cp-root \
    --not-before=2024-01-01T00:00:00Z --not-after=2027-01-01T00:00:00Z \
    --key ISD2/AS210/cp-root.key \
    ISD2/AS210/cp-root.json ISD2/AS210/cp-root.crt ISD2/AS210/cp-root.key

scion-pki certificate create --force --profile=sensitive-voting \
    --not-before=2024-01-01T00:00:00Z --not-after=2027-01-01T00:00:00Z \
    --key ISD2/AS210/cp-voting.key \
    ISD2/AS210/cp-voting.json ISD2/AS210/cp-voting.crt ISD2/AS210/cp-voting.key

scion-pki certificate create --force --profile=regular-voting \
    --not-before=2024-01-01T00:00:00Z --not-after=2027-01-01T00:00:00Z \
    --key ISD2/AS210/cp-regular.key \
    ISD2/AS210/cp-regular.json ISD2/AS210/cp-regular.crt ISD2/AS210/cp-regular.key

# Create TRC for ISD2
cat > ISD2/trc-template.toml << 'TRCEOF'
isd = 2
description = \"ISD 2 - Commercial Network\"
serial_version = 1
base_version = 1
voting_quorum = 1

core_ases = [\"ff00:0:210\"]
authoritative_ases = [\"ff00:0:210\"]
cert_files = [\"AS210/cp-root.crt\", \"AS210/cp-voting.crt\", \"AS210/cp-regular.crt\"]

no_trust_reset = false

[validity]
not_before = 1704067200
validity = \"1096d\"
TRCEOF

scion-pki trc payload --template ISD2/trc-template.toml --out ISD2/trc-payload.der
scion-pki trc sign ISD2/trc-payload.der ISD2/AS210/cp-voting.crt ISD2/AS210/cp-voting.key \
    --out ISD2/ISD2-B1-S1.trc

# Generate CA certificate for ISD2
echo '{\"isd_as\": \"2-ff00:0:210\", \"common_name\": \"2-ff00:0:210 CA Certificate\"}' > ISD2/AS210/cp-ca.json
scion-pki key private ISD2/AS210/cp-ca.key 2>/dev/null
scion-pki certificate create --force --profile=cp-ca \
    --ca ISD2/AS210/cp-root.crt --ca-key ISD2/AS210/cp-root.key \
    --not-before=2024-01-01T00:00:00Z --not-after=2027-01-01T00:00:00Z \
    --key ISD2/AS210/cp-ca.key \
    ISD2/AS210/cp-ca.json ISD2/AS210/cp-ca.crt ISD2/AS210/cp-ca.key

# Generate AS certificate for AS210 (core AS also needs AS cert for signing)
echo '{\"isd_as\": \"2-ff00:0:210\", \"common_name\": \"2-ff00:0:210 AS Certificate\"}' > ISD2/AS210/cp-as.json
scion-pki key private ISD2/AS210/cp-as.key 2>/dev/null
scion-pki certificate create --force --profile=cp-as --bundle \
    --ca ISD2/AS210/cp-ca.crt --ca-key ISD2/AS210/cp-ca.key \
    --not-before=2024-01-01T00:00:00Z --not-after=2026-01-01T00:00:00Z \
    --key ISD2/AS210/cp-as.key \
    ISD2/AS210/cp-as.json ISD2/AS210/cp-as.pem ISD2/AS210/cp-as.key

# Generate AS211 (non-core) PKI
scion-pki key private ISD2/AS211/cp-as.key 2>/dev/null
scion-pki key symmetric ISD2/AS211/master0.key 2>/dev/null
scion-pki key symmetric ISD2/AS211/master1.key 2>/dev/null
echo '{\"isd_as\": \"2-ff00:0:211\", \"common_name\": \"2-ff00:0:211 AS Certificate\"}' > ISD2/AS211/cp-as.json
scion-pki certificate create --force --profile=cp-as --bundle \
    --ca ISD2/AS210/cp-ca.crt --ca-key ISD2/AS210/cp-ca.key \
    --not-before=2024-01-01T00:00:00Z --not-after=2026-01-01T00:00:00Z \
    --key ISD2/AS211/cp-as.key \
    ISD2/AS211/cp-as.json ISD2/AS211/cp-as.pem ISD2/AS211/cp-as.key

# Function to extract the first 16 bytes of key data as raw base64
extract_master_key() {
    # Read base64 content (strip PEM headers), decode, take 16 bytes, re-encode
    sed -n '/BEGIN/,/END/p' \$1 | grep -v -- '-----' | tr -d '\\n' | base64 -d | head -c 16 | base64
}

# Copy files to appropriate AS directories
# AS110 (ISD1 Core) - peers with AS210 (ISD2), needs both TRCs
cp ISD1/ISD1-B1-S1.trc /gen/AS110/certs/
cp ISD2/ISD2-B1-S1.trc /gen/AS110/certs/
extract_master_key ISD1/AS110/master0.key > /gen/AS110/keys/master0.key
extract_master_key ISD1/AS110/master1.key > /gen/AS110/keys/master1.key
cp ISD1/AS110/cp-as.key /gen/AS110/keys/as-signing.key
cp ISD1/AS110/cp-as.pem /gen/AS110/certs/
cp ISD1/AS110/cp-as.pem /gen/AS110/crypto/as/
cp ISD1/AS110/cp-as.key /gen/AS110/crypto/as/

# AS111 (ISD1 Leaf) - peers with AS211 (ISD2), needs both TRCs  
cp ISD1/ISD1-B1-S1.trc /gen/AS111/certs/
cp ISD2/ISD2-B1-S1.trc /gen/AS111/certs/
extract_master_key ISD1/AS111/master0.key > /gen/AS111/keys/master0.key
extract_master_key ISD1/AS111/master1.key > /gen/AS111/keys/master1.key
cp ISD1/AS111/cp-as.key /gen/AS111/keys/as-signing.key
cp ISD1/AS111/cp-as.pem /gen/AS111/certs/
cp ISD1/AS111/cp-as.pem /gen/AS111/crypto/as/
cp ISD1/AS111/cp-as.key /gen/AS111/crypto/as/

# AS210 (ISD2 Core) - peers with AS110 (ISD1), needs both TRCs
cp ISD2/ISD2-B1-S1.trc /gen/AS210/certs/
cp ISD1/ISD1-B1-S1.trc /gen/AS210/certs/
extract_master_key ISD2/AS210/master0.key > /gen/AS210/keys/master0.key
extract_master_key ISD2/AS210/master1.key > /gen/AS210/keys/master1.key
cp ISD2/AS210/cp-as.key /gen/AS210/keys/as-signing.key
cp ISD2/AS210/cp-as.pem /gen/AS210/certs/
cp ISD2/AS210/cp-as.pem /gen/AS210/crypto/as/
cp ISD2/AS210/cp-as.key /gen/AS210/crypto/as/

# AS211 (ISD2 Leaf) - peers with AS111 (ISD1), needs both TRCs
cp ISD2/ISD2-B1-S1.trc /gen/AS211/certs/
cp ISD1/ISD1-B1-S1.trc /gen/AS211/certs/
extract_master_key ISD2/AS211/master0.key > /gen/AS211/keys/master0.key
extract_master_key ISD2/AS211/master1.key > /gen/AS211/keys/master1.key
cp ISD2/AS211/cp-as.key /gen/AS211/keys/as-signing.key
cp ISD2/AS211/cp-as.pem /gen/AS211/certs/
cp ISD2/AS211/cp-as.pem /gen/AS211/crypto/as/
cp ISD2/AS211/cp-as.key /gen/AS211/crypto/as/

echo '  PKI generation complete!'
"

echo ""
echo "✅ Setup complete!"
echo ""
echo "Generated files in $GEN_DIR:"
find "$GEN_DIR" -type f | sort | sed 's|'"$GEN_DIR"'/|  gen/|'
echo ""
echo "Next steps:"
echo "  1. Run 'make up' to start the network"
echo "  2. Run 'make status' to check container health"
echo "  3. Run 'make paths' to discover SCION paths"
